version: '3.4'

services:
  customerreviewsmodule.web:
    volumes:
      - .\CustomerReviewsModule\CustomerReviewsModule.Web:C:\vc-platform\modules\customerreviewsmodule
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc"
